# Generated by Django 4.1.7 on 2023-02-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ser',
            new_name='user',
        ),
    ]
